# -*- coding: utf-8 -*-
"""01_PythonPractice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WMYAdrpizw3vnCilwp-ay2unazbJkwkV

# 01 : Email Validation

Rules for validation:
01. There should be only one @ symbol. 
02. There should be at least one period.
03. Special characters should not come in succession.
04. User name must not have any special characters except period and underscore.
05. Username must not start or end with a special character.
06. Email must not start or end with a special character.
07. Domain name and Domain extension should be at least two characters long.
08. Domain name should be alphabetic.
09. Domain extension can have only period and hyphen as special characters.
10. Maximum length of the email should be 50 and minimum length should be 8.
11. Username must have at least one alphabetic character.
12. There should not be any characters other than a-z, A-Z, 0-9 and [@ . _ -] in the email address.
13. There should not be any whitespace characters in the email address.
"""

import re

def evaluate_email(email):
#    Complete this function
#    return 'Valid' or 'Invalid'
  result = ''
  pattern = re.compile(r"((^[a-zA-Z0-9]+)([\._]{1}|[a-zA-Z0-9]+)[a-zA-Z0-9]+[@]{1}([a-zA-Z]{2,}\.[a-zA-Z0-9\.-]{2,}))")
  if re.fullmatch(pattern, email) and len(email) in range(8,51):
    result = 'Valid'
  else:
    result = 'Invalid'
  return result

email_list = ['brucewayne@jla.com', 'clark_kent@jla.com', '_jonnjonzz@jla.com', 'batman@jla.lead-mem.co.us', 'dianaprince@jla.com', 'victorstone@jla.c0m', 'billybatson@j.com', 'barryallen@jla.c', 'arthurcurry@atlantis.com', 'johnconstantine@jla.c#.us', 'zatannazatara@j1a.com', 'haljordan.@jla.com', 'oliverqueen@jlacom', 'ray_palmer@jla@us', 'carter&hall@jla.com', 'b@jl.us',  'firestorm_equals_engineer_ronald_raymond_plus_doctor_martin_stein@justiceleagueofamerica.com']
print('Email' + ' ' * 95 + 'Result')
for email in email_list:
    result = evaluate_email(email)
    print(f"{email:100s}{result}")